# Generated by Django 5.2.5 on 2025-08-18 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MODERATE', 'Moderate Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical Emergency')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('rainfall_data', models.JSONField(blank=True, null=True)),
                ('river_level', models.FloatField(blank=True, null=True)),
                ('indigenous_indicators', models.JSONField(blank=True, null=True)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.village')),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_method', models.CharField(choices=[('SMS', 'SMS'), ('USSD', 'USSD')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_confirmed', models.BooleanField(default=False)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='alerts.alert')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['village', 'is_active'], name='alerts_aler_village_9c5548_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['alert_level', 'valid_until'], name='alerts_aler_alert_l_e78527_idx'),
        ),
        migrations.AddIndex(
            model_name='alertdelivery',
            index=models.Index(fields=['status', 'sent_at'], name='alerts_aler_status_81fff4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='alertdelivery',
            unique_together={('alert', 'farmer')},
        ),
    ]
