# Generated by Django 5.2.5 on 2025-08-17 19:36

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigKV',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=128, unique=True)),
                ('value', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Core Config KV',
                'verbose_name_plural': 'Core Config KV',
                'db_table': 'core_config_kv',
                'indexes': [models.Index(fields=['key'], name='core_config_key_fcfd3d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('county', models.CharField(blank=True, max_length=128, null=True)),
                ('region', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'verbose_name': 'Village',
                'verbose_name_plural': 'Villages',
                'db_table': 'core_village',
                'indexes': [models.Index(fields=['name'], name='core_villag_name_8443e3_idx')],
            },
        ),
    ]
