# Generated by Django 5.2.5 on 2025-08-17 19:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rainfall', models.FloatField(default=0, help_text='Rainfall in mm')),
                ('risk_level', models.CharField(db_index=True, default='unknown', max_length=20)),
                ('raw', models.JSONField(blank=True, default=dict, help_text='Raw API response')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='core.village')),
            ],
            options={
                'verbose_name': 'Forecast',
                'verbose_name_plural': 'Forecasts',
                'db_table': 'data_forecast',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['risk_level'], name='data_foreca_risk_le_85ee91_idx'), models.Index(fields=['village', 'created_at'], name='data_foreca_village_df1d8c_idx')],
            },
        ),
    ]
