# Generated by Django 5.2.5 on 2025-08-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('fisher', 'Fisher'), ('government', 'Government Official')], default='farmer', max_length=20),
        ),
    ]
