# Generated by Django 5.2.5 on 2025-08-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='msisdn',
            field=models.CharField(blank=True, db_index=True, help_text='Mobile phone number in international format, e.g. +2547...', max_length=32, null=True, unique=True),
        ),
    ]
